# Book settings
title: Unsupervised Quant: A collection of notes on mathematics, statistics, machine learning and quantitiative research (and all the other buzzwords).
author: An Unsupervised Quant
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex
